#!/usr/bin/env bash
# check-emit.sh - Verify lib/emit.sh: active.md, Copilot files (groups, globs, 4,000-character
# split, core file), REVIEW.md, the agent-neutral review.md, the AGENTS.md block, cleanup of
# generated files, determinism, and the --check staleness test.
# Usage: ./tests/check-emit.sh [repo-root]
set -euo pipefail

REPO_ROOT="${1:-$(cd "$(dirname "$0")/.." && pwd)}"
EMIT="$REPO_ROOT/lib/emit.sh"
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

FAILURES=0
fail() { echo "FAIL [$1] $2"; FAILURES=$((FAILURES + 1)); }
has()  { grep -qF -- "$2" "$1" || fail "$3" "$1 lacks: $2"; }
lacks(){ if grep -qF -- "$2" "$1" 2>/dev/null; then fail "$3" "$1 unexpectedly has: $2"; fi; }

new_project() { # name -> sets P and CAT
    P="$T/$1"; CAT="$P/.agents/principles-catalog"
    mkdir -p "$CAT/groups" "$CAT/layers/docs" "$P/.git" "$P/sub"
    echo "0.99.0" > "$CAT/VERSION"
    cat > "$CAT/groups/a.yaml" <<'EOF'
name: a
globs:
  - "**/*.md"
principles:
  - X-ONE
  - X-TWO
EOF
    cat > "$CAT/groups/b.yaml" <<'EOF'
name: b
globs:
  - "**/*.java"
includes:
  - a
principles:
  - SOLID-SRP
EOF
    {
        echo 'name: big'
        echo 'principles:'
        for i in $(seq -w 1 60); do echo "  - BIG-P$i"; done
    } > "$CAT/groups/big.yaml"
    cat > "$CAT/groups/org.yaml" <<'EOF'
name: org
principles:
  - ORG-ONE
EOF
    {
        echo 'X-ONE|1|First principle summary.'
        echo 'X-TWO|2|Second principle summary.'
        echo 'SOLID-SRP|1|A unit has one reason to change.'
        echo 'OWASP-A01|1|Enforce access control on the server.'
        echo 'CODE-CS-DRY|1|One authoritative representation per piece of knowledge.'
        echo 'ORG-ONE|2|Company rule one.'
        echo 'U-ONE|1|Universal one.'
        echo 'D-ONE|1|Docs stack layer one.'
        for i in $(seq -w 1 60); do echo "BIG-P$i|2|Summary for principle number $i that is deliberately long enough to fill the budget."; done
    } > "$CAT/index.tsv"
    printf 'universal:\n  - U-ONE\ntypes:\n  docs:\n    stack: docs\n' > "$CAT/layers/artifact-types.yaml"
    printf '| ID | Title | Summary |\n|----|-------|---------|\n| D-ONE | t | s |\n' > "$CAT/layers/docs/layer-1-universal.md"
    printf '# org baseline\n' > "$CAT/org.principles"
}
emit() { bash "$EMIT" --root "$P" --catalog "$CAT" "$@" >/dev/null; }

# ── 1. a basic project: groups, includes, globs, core file, REVIEW.md ───────────────────────
new_project basic
printf '@b\nOWASP-A01\nCODE-CS-DRY\n' > "$P/.principles"
emit --tools copilot,claude --stacks docs

has "$CAT/active.md" "generated by dot-scout v0.99.0" "active.md marker"
has "$CAT/active.md" "- X-ONE: First principle summary." "active.md entry"
has "$CAT/active.md" "- OWASP-A01: Enforce access control on the server." "active.md bare id"

B="$P/.github/instructions/b.instructions.md"
has "$B" "generated by dot-scout v0.99.0" "copilot marker"
has "$B" '  - "**/*.java"' "copilot globs (own)"
has "$B" '  - "**/*.md"' "copilot globs (from include)"
has "$B" "- SOLID-SRP:" "copilot group principle"
has "$B" "- X-ONE:" "copilot include closure"
[ -f "$P/.github/instructions/a.instructions.md" ] && fail "no file for inactive group" "a.instructions.md was written, but only @b is active"

CORE="$P/.github/instructions/principles-core.instructions.md"
has "$CORE" "- U-ONE: Universal one." "core universal"
has "$CORE" "- D-ONE: Docs stack layer one." "core stack layer 1 (--stacks docs)"
has "$CORE" "- OWASP-A01:" "core bare id"
has "$CORE" '  - "**/*"' "core applies everywhere"
lacks "$CORE" "- SOLID-SRP:" "core does not repeat grouped ids"

R="$P/REVIEW.md"
has "$R" "## Critical - Always flag these" "REVIEW.md critical section"
has "$R" "- OWASP-A01:" "REVIEW.md critical member"
has "$R" "## Important - Flag when violated" "REVIEW.md important section"
has "$R" "- SOLID-SRP:" "REVIEW.md important member"
has "$R" "## Style - Flag as nits" "REVIEW.md style section"
has "$R" "- CODE-CS-DRY:" "REVIEW.md style member"
[ "$(wc -c < "$R")" -le 10100 ] || fail "REVIEW.md budget" "$(wc -c < "$R") characters"

# ── 2. agent-neutral review.md and the AGENTS.md block ──────────────────────────────────────
RM="$P/.agents/instructions/review.md"
has "$RM" "principles-hash:" "review.md hash"
has "$RM" "emit.sh --check" "review.md staleness instruction"
has "$RM" "context.sh" "review.md points at context.sh"
has "$RM" "- OWASP-A01:" "review.md lists principles"
has "$P/AGENTS.md" "<!-- .principles:start" "AGENTS.md block start"
has "$P/AGENTS.md" ".agents/instructions/review.md" "AGENTS.md points at review.md"
has "$P/AGENTS.md" "<!-- .principles:end -->" "AGENTS.md block end"

# ── 3. determinism and idempotence ──────────────────────────────────────────────────────────
snapshot() { (cd "$P" && cat AGENTS.md REVIEW.md .agents/instructions/review.md "$CAT/active.md" .github/instructions/*.md | cksum); }
S1="$(snapshot)"; emit --tools copilot,claude --stacks docs; S2="$(snapshot)"
[ "$S1" = "$S2" ] || fail "determinism" "a second run changed the generated files"
[ "$(grep -c '<!-- .principles:start' "$P/AGENTS.md")" = 1 ] || fail "AGENTS.md idempotent" "managed block was duplicated"

# ── 4. staleness ────────────────────────────────────────────────────────────────────────────
bash "$EMIT" --root "$P" --catalog "$CAT" --check >/dev/null || fail "check fresh" "fresh files reported stale"
echo '!CODE-CS-DRY' >> "$P/.principles"
if bash "$EMIT" --root "$P" --catalog "$CAT" --check >/dev/null; then fail "check stale" ".principles changed but --check said ok"; fi
emit --tools copilot,claude --stacks docs
bash "$EMIT" --root "$P" --catalog "$CAT" --check >/dev/null || fail "check after emit" "still stale after re-emitting"
lacks "$CAT/active.md" "CODE-CS-DRY" "exclusion reaches active.md"

# ── 5. AGENTS.md: existing content is kept, user files are never touched ────────────────────
new_project existing
printf '@a\n' > "$P/.principles"
printf '# Our agent rules\n\nBe kind.\n' > "$P/AGENTS.md"
mkdir -p "$P/.github/instructions"
printf -- '---\napplyTo: "**/*"\n---\n# Mine\n' > "$P/.github/instructions/mine.instructions.md"
printf '# Our review rules\n' > "$P/REVIEW.md"
emit --tools copilot
has "$P/AGENTS.md" "Be kind." "AGENTS.md keeps existing content"
has "$P/AGENTS.md" "<!-- .principles:start" "AGENTS.md block appended"
[ -f "$P/.github/instructions/mine.instructions.md" ] || fail "user instruction file" "unmarked file was deleted"
has "$P/REVIEW.md" "Our review rules" "hand-written REVIEW.md untouched (claude disabled)"

# ── 6. generated files that no longer apply are removed ─────────────────────────────────────
new_project cleanup
printf '@a\n' > "$P/.principles"
emit --tools copilot,claude
[ -f "$P/.github/instructions/a.instructions.md" ] && [ -f "$P/REVIEW.md" ] || fail "setup" "expected generated files"
printf '@org\n' > "$P/.principles"
emit --tools copilot
[ ! -f "$P/.github/instructions/a.instructions.md" ] || fail "stale group file" "a.instructions.md should be deleted"
[ ! -f "$P/REVIEW.md" ] || fail "stale REVIEW.md" "generated REVIEW.md should be deleted when claude is off"
[ -f "$P/.github/instructions/org.instructions.md" ] || fail "new group file" "org.instructions.md missing"

# ── 7. 4,000-character split ────────────────────────────────────────────────────────────────
new_project big
printf '@big\n' > "$P/.principles"
emit --tools copilot
n=0
for f in "$P"/.github/instructions/big-*.instructions.md; do
    [ -f "$f" ] || continue
    n=$((n + 1))
    [ "$(wc -c < "$f")" -le 4100 ] || fail "split size" "$f is $(wc -c < "$f") bytes"
    has "$f" "generated by dot-scout" "split file marker"
    has "$f" "applyTo:" "split file frontmatter"
done
[ "$n" -ge 2 ] || fail "split" "expected the big group to split into several files, got $n"
[ ! -f "$P/.github/instructions/big.instructions.md" ] || fail "split naming" "unsplit file left behind"
total=$(cat "$P"/.github/instructions/big-*.instructions.md | grep -c '^- BIG-P')
[ "$total" = 60 ] || fail "split completeness" "expected 60 principles across the split files, got $total"

# ── 8. governance sections: lock, waiver ────────────────────────────────────────────────────
new_project gov
printf ':lock ORG-ONE\n' > "$CAT/org.principles"
printf '@a\n!ORG-ONE\n:waive X-TWO until 2999-01-01 "legacy API, see ADR-12"\n' > "$P/.principles"
emit --tools claude
RM="$P/.agents/instructions/review.md"
has "$RM" "- ORG-ONE: Company rule one. *(required by your organization)*" "locked principle marked"
has "$P/REVIEW.md" "## Critical - Always flag these" "locked goes to critical"
has "$RM" "## Waivers" "waivers section"
has "$RM" "X-TWO until 2999-01-01" "waiver listed"
has "$RM" "legacy API, see ADR-12" "waiver reason"
has "$RM" "Locked principles that a project tried to exclude" "override section"
lacks "$CAT/active.md" "X-TWO" "waived principle not active"
has "$CAT/active.md" "ORG-ONE" "locked principle active"

# ── 9. --dry-run writes nothing; stacks are remembered in install.cfg ───────────────────────
new_project dry
printf '@a\n' > "$P/.principles"
bash "$EMIT" --root "$P" --catalog "$CAT" --tools copilot --dry-run >/dev/null
[ ! -e "$P/.agents/instructions" ] && [ ! -e "$CAT/active.md" ] && [ ! -e "$P/AGENTS.md" ] \
    || fail "dry run" "files were written"
printf 'copilot-review\nvendor\n' > "$CAT/install.cfg"
emit --stacks docs
has "$CAT/install.cfg" "stack-docs" "stacks remembered"
has "$CAT/install.cfg" "copilot-review" "install.cfg targets kept"
emit
has "$P/.github/instructions/principles-core.instructions.md" "D-ONE" "stacks reused from install.cfg"

# ── 10. --check hashes the inputs: it never resolves, and stack order does not matter ────────
new_project order
printf '@a\n' > "$P/.principles"
mkdir -p "$CAT/layers/code"
printf '| ID | Title | Summary |\n|----|-------|---------|\n| C-ONE | t | s |\n' > "$CAT/layers/code/layer-1-universal.md"
printf 'copilot-review\n' > "$CAT/install.cfg"
emit --stacks docs,code
bash "$EMIT" --root "$P" --catalog "$CAT" --check >/dev/null || fail "check after emit" "stale right after emit --stacks docs,code"
emit --stacks code,docs
bash "$EMIT" --root "$P" --catalog "$CAT" --check >/dev/null || fail "stack order" "the same stacks in another order changed the hash"
broken="$T/broken-lib"; mkdir -p "$broken"; cp "$REPO_ROOT"/lib/*.sh "$broken/"
printf '#!/usr/bin/env bash\necho "resolve.sh must not run for --check" >&2\nexit 99\n' > "$broken/resolve.sh"
bash "$broken/emit.sh" --root "$P" --catalog "$CAT" --check >/dev/null 2>&1 \
    || fail "check does not resolve" "--check ran resolve.sh (it must only hash the inputs)"
printf '@a\n@b\n' > "$P/.principles"
if bash "$broken/emit.sh" --root "$P" --catalog "$CAT" --check >/dev/null 2>&1; then
    fail "check sees an input change" "--check missed a changed .principles file"
fi
printf '@a\n' > "$P/.principles"
printf 'X-ONE|1|A different summary.\n' >> "$CAT/index.tsv"
if bash "$broken/emit.sh" --root "$P" --catalog "$CAT" --check >/dev/null 2>&1; then
    fail "check sees a catalog change" "--check missed a changed index.tsv"
fi

if [ "$FAILURES" -gt 0 ]; then
    echo "$FAILURES emit check(s) failed."
    exit 1
fi
echo "OK  emit.sh: deterministic review files, split, cleanup, governance sections and staleness check."
