#!/usr/bin/env bash
# check-uninstall-purge.sh - Verify `uninstall.sh --purge`: removes the user's .principles files and
# leftovers, keeps everything that is not this project's, supports --dry-run, never edits docs.
# Usage: ./tests/check-uninstall-purge.sh [repo-root]
set -euo pipefail

REPO_ROOT="${1:-$(cd "$(dirname "$0")/.." && pwd)}"
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT
export HOME="$T/home"; mkdir -p "$HOME"

FAILURES=0
fail() { echo "FAIL [$1] $2"; FAILURES=$((FAILURES + 1)); }
gone() { [ ! -e "$1" ] || fail "$2" "$1 should be removed"; }
kept() { [ -e "$1" ] || fail "$2" "$1 should be kept"; }

P="$T/project"
mkdir -p "$P/.git" "$P/server/src" "$P/docs" "$P/node_modules/lib" "$P/build/out" \
         "$P/vendor-repo/.git" "$P/.claude/worktrees/feature" "$P/.agents/instructions"

# What belongs to .principles
printf '@java\n' > "$P/.principles"
printf '@docs\n' > "$P/docs/.principles"
printf '!SOLID-SRP\n' > "$P/server/.principles"
printf '../org\n' > "$P/.principles-extra"
printf '{"findings":[],"summary":{"principle_source":"x"}}\n' > "$P/audit-output.json"
printf '<!-- generated by dot-scout v0.15.0 - x -->\n# review\n' > "$P/.agents/instructions/review.md"
printf '%s\n' '<!-- .principles:start -->' '## Code review' 'Follow it.' '<!-- .principles:end -->' > "$P/AGENTS.md"

# What is not ours and must survive: dependencies, build output, nested repo, git worktree, user files
printf '@java\n' > "$P/node_modules/lib/.principles"
printf '@java\n' > "$P/build/out/.principles"
printf '@java\n' > "$P/vendor-repo/.principles"
printf 'gitdir: /elsewhere\n' > "$P/.claude/worktrees/feature/.git"
printf '@java\n' > "$P/.claude/worktrees/feature/.principles"
printf '# our own conventions\n' > "$P/.agents/instructions/core.md"

# .gitignore with the block the old installer wrote, between lines of the user's own
printf 'build/\n\n# Generated by .principles\naudit-output.json\n\nnode_modules/\n' > "$P/.gitignore"
# Docs that mention the tooling: reported, never edited
printf 'Run /dot-scout to refresh the .principles files.\n' > "$P/docs/notes.md"
cp "$P/docs/notes.md" "$T/notes.before"

# An audit-output.json that is not dot-audit's must never be deleted
Q="$T/other"; mkdir -p "$Q/.git"
printf '{"unrelated": true}\n' > "$Q/audit-output.json"
printf '@java\n' > "$Q/.principles"

run() { bash "$REPO_ROOT/uninstall.sh" "$@" 2>&1; }

# ── 1. plain uninstall keeps the user's configuration and says how to remove it ─────────────
out="$(run "$P")" || fail "plain uninstall" "exited non-zero: $out"
kept "$P/.principles" "plain keeps .principles"
kept "$P/docs/.principles" "plain keeps nested .principles"
kept "$P/.principles-extra" "plain keeps .principles-extra"
gone "$P/.agents/instructions/review.md" "plain removes generated review.md"
grep -q -- '--purge' <<< "$out" || fail "hint" "plain uninstall did not mention --purge"

# ── 2. --purge --dry-run lists, and changes nothing ─────────────────────────────────────────
printf '<!-- generated by dot-scout v0.15.0 - x -->\n# review\n' > "$P/.agents/instructions/review.md"
snapshot() { (cd "$P" && find . -type f -not -path './.git/*' | sort | xargs cksum | cksum); }
S1="$(snapshot)"
out="$(run "$P" --purge --dry-run)" || fail "dry run" "exited non-zero: $out"
S2="$(snapshot)"
[ "$S1" = "$S2" ] || fail "dry run changes" "--dry-run modified files"
grep -q 'docs/.principles' <<< "$out" || fail "dry run lists" "docs/.principles not listed"
grep -q 'Would remove' <<< "$out" || fail "dry run wording" "missing 'Would remove'"
if run "$P" --dry-run >/dev/null; then fail "dry run alone" "--dry-run without --purge should be an error"; fi
if run "$P" --purge --target vendor >/dev/null; then fail "purge with target" "--purge with --target should be an error"; fi

# ── 3. --purge removes everything that is ours ──────────────────────────────────────────────
out="$(run "$P" --purge)" || fail "purge" "exited non-zero: $out"
gone "$P/.principles" "purge .principles"
gone "$P/docs/.principles" "purge docs/.principles"
gone "$P/server/.principles" "purge server/.principles"
gone "$P/.principles-extra" "purge .principles-extra"
gone "$P/audit-output.json" "purge audit-output.json"
gone "$P/.agents/instructions/review.md" "purge review.md"
gone "$P/AGENTS.md" "purge AGENTS.md block (nothing else in the file)"

# ── 4. ... and nothing else ─────────────────────────────────────────────────────────────────
kept "$P/node_modules/lib/.principles" "dependencies untouched"
kept "$P/build/out/.principles" "build output untouched"
kept "$P/vendor-repo/.principles" "nested repository untouched"
kept "$P/.claude/worktrees/feature/.principles" "git worktree untouched"
kept "$P/.agents/instructions/core.md" "user's own instruction file untouched"
kept "$Q/.principles" "purging one project leaves another project untouched"
grep -q 'left 2' <<< "$out" || fail "nested repos reported" "expected a note about skipped nested .principles files"

# purging a project whose audit-output.json is not dot-audit's: .principles goes, that file stays
run "$Q" --purge >/dev/null || fail "purge other project" "exited non-zero"
gone "$Q/.principles" "other project's .principles purged"
kept "$Q/audit-output.json" "unrelated audit-output.json untouched"

# .gitignore: only the block is gone
grep -q 'Generated by .principles' "$P/.gitignore" && fail ".gitignore block" "block still present"
grep -qx 'build/' "$P/.gitignore" || fail ".gitignore keeps own lines" "build/ lost"
grep -qx 'node_modules/' "$P/.gitignore" || fail ".gitignore keeps own lines" "node_modules/ lost"
grep -qx 'audit-output.json' "$P/.gitignore" && fail ".gitignore audit-output" "audit-output.json line still present"

# docs are reported, never edited
cmp -s "$P/docs/notes.md" "$T/notes.before" || fail "docs untouched" "docs/notes.md was modified"
grep -q 'docs/notes.md' <<< "$out" || fail "mentions reported" "docs/notes.md mention not listed"

# ── 5. a second purge on a clean project is a no-op that succeeds ───────────────────────────
out="$(run "$P" --purge)" || fail "second purge" "exited non-zero: $out"
grep -q 'No .principles files or leftovers found' <<< "$out" || fail "second purge message" "got: $out"

if [ "$FAILURES" -gt 0 ]; then
    echo "$FAILURES purge check(s) failed."
    exit 1
fi
echo "OK  uninstall --purge removes your .principles files and leftovers, keeps what is not yours, and supports --dry-run."
