#!/usr/bin/env bash
# check-uninstall-generated.sh - Verify that uninstall removes files generated by the current
# dot-scout (marker without slash, REVIEW.md) and keeps files the user wrote.
# Usage: ./tests/check-uninstall-generated.sh [repo-root]
set -euo pipefail

REPO_ROOT="${1:-$(cd "$(dirname "$0")/.." && pwd)}"
TEST_ROOT="$(mktemp -d)"
TEST_HOME="$TEST_ROOT/home"
trap 'rm -rf "$TEST_ROOT"' EXIT
mkdir -p "$TEST_HOME"

fail() { echo "FAIL [$1] $2"; exit 1; }

run_uninstall() {
    HOME="$TEST_HOME" bash "$REPO_ROOT/uninstall.sh" "$1" >/dev/null 2>&1
}

# --- Case 1: scout-generated files (current and legacy markers) are removed ---
P1="$TEST_ROOT/generated"
mkdir -p "$P1/.github/instructions"
printf '%s\n' '<!-- generated by dot-scout v0.14.0 - do not edit manually -->' '---' 'applyTo: "**/*"' '---' \
    > "$P1/.github/instructions/current.instructions.md"
printf '%s\n' '<!-- generated by /dot-scout v0.12.0 -->' '---' 'applyTo: "**/*"' '---' \
    > "$P1/.github/instructions/legacy.instructions.md"
printf '%s\n' '---' 'applyTo: "**/*"' '---' '# Mine' \
    > "$P1/.github/instructions/user.instructions.md"
printf '%s\n' '<!-- generated by dot-scout v0.14.0 - do not edit manually -->' '# Code Review Rules' \
    > "$P1/REVIEW.md"

run_uninstall "$P1"

[ ! -e "$P1/.github/instructions/current.instructions.md" ] \
    || fail "current marker" "instruction file generated by current dot-scout was not removed"
[ ! -e "$P1/.github/instructions/legacy.instructions.md" ] \
    || fail "legacy marker" "instruction file with the legacy marker was not removed"
[ -f "$P1/.github/instructions/user.instructions.md" ] \
    || fail "user file" "unmarked user instruction file was removed"
[ ! -e "$P1/REVIEW.md" ] \
    || fail "REVIEW.md" "scout-generated REVIEW.md was not removed"

# --- Case 2: a hand-written REVIEW.md is never touched ---
P2="$TEST_ROOT/handwritten"
mkdir -p "$P2"
printf '%s\n' '# Our review rules' > "$P2/REVIEW.md"

run_uninstall "$P2"

[ -f "$P2/REVIEW.md" ] || fail "user REVIEW.md" "hand-written REVIEW.md was removed"

# --- Case 3: review.md and the AGENTS.md block written by emit.sh ---
BLOCK=$'<!-- .principles:start -->\n## Code review\n\nFollow `.agents/instructions/review.md`.\n<!-- .principles:end -->'

# 3a: emit.sh created AGENTS.md itself (the block is all there is) -> the file goes away
P3="$TEST_ROOT/emitted-new"
mkdir -p "$P3/.agents/instructions"
printf '%s\n' '<!-- generated by dot-scout v0.16.0 - do not edit manually -->' '# Code review principles' \
    > "$P3/.agents/instructions/review.md"
printf '%s\n' "$BLOCK" > "$P3/AGENTS.md"
run_uninstall "$P3"
[ ! -e "$P3/.agents/instructions/review.md" ] || fail "review.md" "scout-generated review.md was not removed"
[ ! -e "$P3/AGENTS.md" ] || fail "AGENTS.md created by emit" "AGENTS.md held only the managed block and should be removed"

# 3b: AGENTS.md had other content -> only the block is removed
P4="$TEST_ROOT/emitted-existing"
mkdir -p "$P4/.agents/instructions"
printf '%s\n' '<!-- generated by dot-scout v0.16.0 - do not edit manually -->' '# Code review principles' \
    > "$P4/.agents/instructions/review.md"
{ printf '# Our agent rules\n\nBe kind.\n\n'; printf '%s\n' "$BLOCK"; } > "$P4/AGENTS.md"
run_uninstall "$P4"
[ -f "$P4/AGENTS.md" ] || fail "AGENTS.md with content" "user content was deleted with the block"
grep -q 'Be kind.' "$P4/AGENTS.md" || fail "AGENTS.md content" "user content is gone"
! grep -q 'principles:start' "$P4/AGENTS.md" || fail "AGENTS.md block" "managed block was not removed"

# 3c: a hand-written review.md (no marker) is never touched
P5="$TEST_ROOT/handwritten-review"
mkdir -p "$P5/.agents/instructions"
printf '%s\n' '# Our own review guide' > "$P5/.agents/instructions/review.md"
run_uninstall "$P5"
[ -f "$P5/.agents/instructions/review.md" ] || fail "user review.md" "hand-written review.md was removed"

echo "OK  Uninstall removes scout-generated review files and keeps user files."
