#!/usr/bin/env bash
# check-uninstall-generated.sh - Verify that uninstall removes files generated by the current
# dot-scout (marker without slash, REVIEW.md) and keeps files the user wrote.
# Usage: ./tests/check-uninstall-generated.sh [repo-root]
set -euo pipefail

REPO_ROOT="${1:-$(cd "$(dirname "$0")/.." && pwd)}"
TEST_ROOT="$(mktemp -d)"
TEST_HOME="$TEST_ROOT/home"
trap 'rm -rf "$TEST_ROOT"' EXIT
mkdir -p "$TEST_HOME"

fail() { echo "FAIL [$1] $2"; exit 1; }

run_uninstall() {
    HOME="$TEST_HOME" bash "$REPO_ROOT/uninstall.sh" "$1" >/dev/null 2>&1
}

# --- Case 1: scout-generated files (current and legacy markers) are removed ---
P1="$TEST_ROOT/generated"
mkdir -p "$P1/.github/instructions"
printf '%s\n' '<!-- generated by dot-scout v0.14.0 - do not edit manually -->' '---' 'applyTo: "**/*"' '---' \
    > "$P1/.github/instructions/current.instructions.md"
printf '%s\n' '<!-- generated by /dot-scout v0.12.0 -->' '---' 'applyTo: "**/*"' '---' \
    > "$P1/.github/instructions/legacy.instructions.md"
printf '%s\n' '---' 'applyTo: "**/*"' '---' '# Mine' \
    > "$P1/.github/instructions/user.instructions.md"
printf '%s\n' '<!-- generated by dot-scout v0.14.0 - do not edit manually -->' '# Code Review Rules' \
    > "$P1/REVIEW.md"

run_uninstall "$P1"

[ ! -e "$P1/.github/instructions/current.instructions.md" ] \
    || fail "current marker" "instruction file generated by current dot-scout was not removed"
[ ! -e "$P1/.github/instructions/legacy.instructions.md" ] \
    || fail "legacy marker" "instruction file with the legacy marker was not removed"
[ -f "$P1/.github/instructions/user.instructions.md" ] \
    || fail "user file" "unmarked user instruction file was removed"
[ ! -e "$P1/REVIEW.md" ] \
    || fail "REVIEW.md" "scout-generated REVIEW.md was not removed"

# --- Case 2: a hand-written REVIEW.md is never touched ---
P2="$TEST_ROOT/handwritten"
mkdir -p "$P2"
printf '%s\n' '# Our review rules' > "$P2/REVIEW.md"

run_uninstall "$P2"

[ -f "$P2/REVIEW.md" ] || fail "user REVIEW.md" "hand-written REVIEW.md was removed"

echo "OK  Uninstall removes scout-generated review files and keeps user files."
