#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# emit.sh — Write the generated review files from the resolved principle set. Deterministic:
# the same .principles hierarchy and catalog always produce byte-identical files.
#
# Usage: emit.sh [--root DIR] [--catalog DIR] [--tools copilot,claude] [--stacks docs,code]
#                [--no-agents] [--check] [--dry-run]
#
# The active set is the union of the set resolved for every directory that holds a .principles
# file (or for the root alone if there are none), so it lists what applies anywhere in the repo.
#
# Writes:
#   <catalog>/active.md                        - `- ID: Summary` for every active principle
#   .agents/instructions/review.md             - agent-neutral review instructions (always)
#   AGENTS.md                                  - a short managed block pointing at review.md
#   .github/instructions/<group>.instructions.md  - Copilot Code Review, one per active @group
#   REVIEW.md                                  - Claude Code Review
# Copilot and Claude files are written only for the enabled tools: --tools, else the review
# targets in <catalog>/install.cfg, else signal files (.github/instructions, CLAUDE.md, ...).
# Files that were generated earlier but no longer apply are deleted; files without the
# "generated by dot-scout" marker are never touched.
#
# --check   Write nothing. Exit 0 if review.md matches the current .principles files and catalog,
#           1 if it is missing or stale.
# --stacks  Artifact stacks detected for the repo (docs, code, ...): their Layer 1 principles are
#           added to the core Copilot file.
set -euo pipefail
# shellcheck source=principles-common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/principles-common.sh"

ROOT=""; CATALOG=""; TOOLS=""; STACKS=""; CHECK=0; DRY=0; AGENTS=1
while [ $# -gt 0 ]; do
    case "$1" in
        --root)      ROOT="$2"; shift 2 ;;
        --catalog)   CATALOG="$2"; shift 2 ;;
        --tools)     TOOLS="$2"; shift 2 ;;
        --stacks)    STACKS="$2"; shift 2 ;;
        --no-agents) AGENTS=0; shift ;;
        --check)     CHECK=1; shift ;;
        --dry-run)   DRY=1; shift ;;
        -h|--help)   sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *)           echo "emit.sh: unknown argument $1" >&2; exit 2 ;;
    esac
done

[ -n "$ROOT" ] || ROOT="$(pc_git_root "$(pwd)")"
ROOT="$(cd "$ROOT" && pwd)"
[ -n "$CATALOG" ] || CATALOG="$(pc_default_catalog "$ROOT")"
[ -d "$CATALOG/groups" ] || { echo "emit.sh: no catalog at $CATALOG (run install.sh vendor)" >&2; exit 2; }
CATALOG="$(cd "$CATALOG" && pwd)"

VERSION="dev"
[ -f "$CATALOG/VERSION" ] && VERSION="$(tr -d '[:space:]' < "$CATALOG/VERSION")"
MARKER="<!-- generated by dot-scout v$VERSION - do not edit manually, re-run dot-scout to refresh -->"
MARKER_RE='<!-- generated by /\?dot-scout'
pc_load_index "$CATALOG"

# ── 1. resolve every directory that has a .principles file ───────────────────────────────────
declare -a DIRS=()
while IFS= read -r f; do DIRS+=("$(dirname "$f")"); done < <(
    find "$ROOT" \( -name node_modules -o -name .git -o -name .agents \) -prune -o \
         -type f -name .principles -print | awk '{ print gsub("/","/") " " $0 }' | sort -n -k1,1 -k2 | cut -d' ' -f2-)
[ "${#DIRS[@]}" -gt 0 ] || DIRS=("$ROOT")

# ── staleness hash over the INPUTS, so --check needs no resolving ────────────────────────────
# The generated files are a function of: the .principles files, the org baseline, the catalog's
# groups, layers and index, and the detected stacks. The resolved result can only change when one
# of these changes, or (with :waive) when the date passes a waiver's end date, so the date is part
# of the hash only when a waiver exists. Hashing inputs takes a fraction of a second even with
# many .principles files, which is what makes a check before every review affordable.
CFG="$CATALOG/install.cfg"
REVIEW_MD="$ROOT/.agents/instructions/review.md"
STACKS_CLI="$STACKS"
# stacks: the command line, else install.cfg, else the header of the review.md written last time
if [ -z "$STACKS" ] && [ -f "$CFG" ]; then
    STACKS="$(sed -n 's/^stack-\(.*\)$/\1/p' "$CFG" | tr '\n' ',')"
fi
if [ -z "$STACKS" ] && [ -f "$REVIEW_MD" ]; then
    STACKS="$(sed -n 's/^<!-- principles-stacks: \(.*\) -->$/\1/p' "$REVIEW_MD" | head -1)"
fi
# sorted and unique: the same set always gives the same hash and the same files
STACKS="$(printf '%s' "$STACKS" | tr ',' '\n' | sed '/^$/d' | sort -u | tr '\n' ',' | sed 's/,$//')"
STACKS_FOR_HASH="$STACKS"
declare -a INPUT_FILES=()
for d in "${DIRS[@]}"; do [ -f "$d/.principles" ] && INPUT_FILES+=("$d/.principles"); done
[ -f "$CATALOG/org.principles" ] && INPUT_FILES+=("$CATALOG/org.principles")
HASH_TODAY=""
if [ "${#INPUT_FILES[@]}" -gt 0 ] && grep -qs '^[[:space:]]*:waive' "${INPUT_FILES[@]}"; then
    HASH_TODAY="$(pc_today)"
fi
HASH="$(
    {
        printf '%s\n' "${INPUT_FILES[@]+"${INPUT_FILES[@]}"}" | sed "s#^$ROOT##"
        [ "${#INPUT_FILES[@]}" -gt 0 ] && cat "${INPUT_FILES[@]}"
        cat "$CATALOG"/groups/*.yaml
        [ -f "$CATALOG/layers/artifact-types.yaml" ] && cat "$CATALOG/layers/artifact-types.yaml"
        compgen -G "$CATALOG/layers/*/layer-1-universal.md" >/dev/null && cat "$CATALOG"/layers/*/layer-1-universal.md
        [ -f "$CATALOG/index.tsv" ] && cat "$CATALOG/index.tsv"
        printf 'stacks=%s\ntoday=%s\n' "$STACKS_FOR_HASH" "$HASH_TODAY"
    } | tr -d '\r' | cksum | cut -d' ' -f1
)"

if [ "$CHECK" = 1 ]; then
    if [ ! -f "$REVIEW_MD" ]; then echo "stale: $REVIEW_MD is missing"; exit 1; fi
    stored="$(sed -n 's/^<!-- principles-hash: \([0-9]*\) -->$/\1/p' "$REVIEW_MD" | head -1)"
    if [ "$stored" != "$HASH" ]; then
        echo "stale: .principles files or the catalog changed since review.md was generated"
        exit 1
    fi
    echo "ok: review.md is up to date"
    exit 0
fi

declare -a ORDER=() GROUPS_SEEN=()
declare -A ACTIVE=() LOCKED=() IS_GROUP=()
declare -a WAIVERS=() WARNINGS=() OVERRIDES=()
for d in "${DIRS[@]}"; do
    out="$(bash "$PC_BIN_DIR/resolve.sh" --catalog "$CATALOG" --format full "$d")"
    rel="${d#$ROOT}"; rel="${rel#/}"; rel="${rel:-.}"
    while IFS='|' read -r kind a b c e; do
        case "$kind" in
            ACTIVE)
                if [ -z "${ACTIVE[$a]+_}" ]; then ACTIVE["$a"]=1; ORDER+=("$a"); fi
                [ "$c" = "locked" ] && LOCKED["$a"]=1 ;;
            GROUP)
                if [ -z "${IS_GROUP[$a]+_}" ]; then IS_GROUP["$a"]=1; GROUPS_SEEN+=("$a"); fi ;;
            WAIVED)        WAIVERS+=("$a|$b|$c|$rel") ;;
            LOCK-OVERRIDE) OVERRIDES+=("$a|$b") ;;
            WARN)          WARNINGS+=("$a") ;;
        esac
    done <<< "$out"
done

# ── 3. which tools get files ─────────────────────────────────────────────────────────────────
COPILOT=0; CLAUDE=0
if [ -n "$TOOLS" ]; then
    case ",$TOOLS," in *,copilot,*) COPILOT=1 ;; esac
    case ",$TOOLS," in *,claude,*)  CLAUDE=1 ;; esac
elif [ -f "$CATALOG/install.cfg" ]; then
    grep -qx 'copilot-review' "$CATALOG/install.cfg" && COPILOT=1
    grep -qx 'claude-review' "$CATALOG/install.cfg" && CLAUDE=1
else
    { [ -f "$ROOT/.github/copilot-instructions.md" ] || compgen -G "$ROOT/.github/instructions/*.instructions.md" >/dev/null; } && COPILOT=1
    { [ -f "$ROOT/CLAUDE.md" ] || [ -d "$ROOT/.claude" ] || [ -f "$ROOT/REVIEW.md" ]; } && CLAUDE=1
fi

# ── helpers ──────────────────────────────────────────────────────────────────────────────────
title_case() { echo "$1" | awk -F- '{ for (i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); print }' OFS=' '; }
declare -a WRITTEN=() DELETED=()

write_file() { # path, content
    local path="$1" content="$2"
    if [ "$DRY" = 1 ]; then WRITTEN+=("${path#$ROOT/} (dry run, ${#content} chars)"); return; fi
    mkdir -p "$(dirname "$path")"
    printf '%s\n' "$content" > "$path"
    WRITTEN+=("${path#$ROOT/} (${#content} chars)")
}
delete_generated() { # path: delete only if it carries the scout marker
    local path="$1"
    [ -f "$path" ] && grep -q "$MARKER_RE" "$path" 2>/dev/null || return 0
    [ "$DRY" = 1 ] || rm -f "$path"
    DELETED+=("${path#$ROOT/}")
}

# Universal + stack Layer 1 IDs (for the core file and the agent-neutral list)
declare -a UNIVERSAL=() STACK_L1=()
if [ -f "$CATALOG/layers/artifact-types.yaml" ]; then
    while IFS= read -r id; do UNIVERSAL+=("${id^^}"); done < <(pc_yaml_list "$CATALOG/layers/artifact-types.yaml" universal)
fi
if [ -n "$STACKS_CLI" ] && [ "$DRY" = 0 ] && [ -f "$CFG" ]; then
    # remember the detected stacks so a later `install.sh vendor` refresh keeps them
    { grep -v '^stack-' "$CFG" || true; echo "$STACKS" | tr ',' '\n' | sed '/^$/d; s/^/stack-/'; } \
        | sort -u > "$CFG.tmp" && mv "$CFG.tmp" "$CFG"
fi
IFS=',' read -ra STACK_LIST <<< "$STACKS"
for st in "${STACK_LIST[@]}"; do
    [ -n "$st" ] || continue
    l1="$CATALOG/layers/$st/layer-1-universal.md"
    [ -f "$l1" ] || { WARNINGS+=("no Layer 1 file for stack '$st'"); continue; }
    while IFS= read -r id; do STACK_L1+=("$id"); done \
        < <(sed -nE 's/^\| ([A-Z0-9]+(-[A-Z0-9]+)+) \|.*/\1/p' "$l1" | tr -d '\r')
done

# ── 4. active.md ─────────────────────────────────────────────────────────────────────────────
ACTIVE_MD="$MARKER"$'\n# Active Principles\n'
for id in "${ORDER[@]+"${ORDER[@]}"}"; do
    [ -n "${PC_SUMMARY[$id]+_}" ] || WARNINGS+=("$id is not in index.tsv (summary '-')")
    ACTIVE_MD+=$'\n'"- $id: ${PC_SUMMARY[$id]:--}"
done
write_file "$CATALOG/active.md" "$ACTIVE_MD"

# ── 5. Copilot Code Review: one file per active @group, plus a core file ─────────────────────
emit_copilot_group() { # name title globs-newline-list, then lines on stdin
    local name="$1" title="$2" globs="$3"
    local header="$MARKER"$'\n---\napplyTo:'
    while IFS= read -r g; do [ -n "$g" ] && header+=$'\n'"  - \"$g\""; done <<< "$globs"
    header+=$'\n---\n# '"$title"$'\n'
    local -a chunks=(); local current="$header" line
    while IFS= read -r line; do
        if [ "${#current}" -gt "${#header}" ] && [ $(( ${#current} + ${#line} + 1 )) -gt 4000 ]; then
            chunks+=("$current"); current="$header"
        fi
        current+=$'\n'"$line"
    done
    chunks+=("$current")
    local i=1
    for c in "${chunks[@]}"; do
        local fname="$name"
        [ "${#chunks[@]}" -gt 1 ] && fname="$name-$i"
        write_file "$ROOT/.github/instructions/$fname.instructions.md" "$c"
        KEEP["$ROOT/.github/instructions/$fname.instructions.md"]=1
        i=$((i + 1))
    done
}

declare -A KEEP=()
if [ "$COPILOT" = 1 ]; then
    declare -A IN_GROUP=()
    for g in "${GROUPS_SEEN[@]+"${GROUPS_SEEN[@]}"}"; do
        [ -f "$CATALOG/groups/$g.yaml" ] || continue
        lines=""
        while IFS= read -r id; do
            case "$id" in '#WARN|'*|'') continue ;; esac
            id="${id^^}"
            [ -n "${ACTIVE[$id]+_}" ] || continue
            IN_GROUP["$id"]=1
            case $'\n'"$lines"$'\n' in *$'\n'"- $id: "*) continue ;; esac
            lines+="${lines:+$'\n'}- $id: ${PC_SUMMARY[$id]:--}"
        done < <(pc_group_ids "$CATALOG" "$g")
        [ -n "$lines" ] || continue
        globs="$(pc_group_globs "$CATALOG" "$g" | awk '!seen[$0]++')"
        [ -n "$globs" ] || globs='**/*'
        emit_copilot_group "$g" "$(title_case "$g") Principles" "$globs" <<< "$lines"
    done
    core=""
    declare -A IN_CORE=()
    for id in "${UNIVERSAL[@]+"${UNIVERSAL[@]}"}" "${STACK_L1[@]+"${STACK_L1[@]}"}"; do
        [ -n "${IN_CORE[$id]+_}" ] && continue
        IN_CORE["$id"]=1; core+="${core:+$'\n'}- $id: ${PC_SUMMARY[$id]:--}"
    done
    for id in "${ORDER[@]+"${ORDER[@]}"}"; do
        [ -n "${IN_GROUP[$id]+_}" ] && continue
        [ -n "${IN_CORE[$id]+_}" ] && continue
        IN_CORE["$id"]=1; core+="${core:+$'\n'}- $id: ${PC_SUMMARY[$id]:--}"
    done
    [ -n "$core" ] && emit_copilot_group "principles-core" "Core Principles" '**/*' <<< "$core"
fi
# remove generated Copilot files that no longer apply
for f in "$ROOT"/.github/instructions/*.instructions.md; do
    [ -f "$f" ] || continue
    [ -n "${KEEP[$f]+_}" ] && continue
    delete_generated "$f"
done

# ── 6. severity buckets (shared by REVIEW.md and review.md) ──────────────────────────────────
declare -a CRIT=() IMPORTANT=() STYLE=()
classify() { # sets CLASS to crit | important | style (no subshell: those are slow on Windows)
    local id="$1"
    if [ -n "${LOCKED[$id]+_}" ]; then CLASS=crit; return; fi
    case "$id" in
        OWASP-*|CODE-SEC-*|SEC-ARCH-*|CODE-CS-FAIL-FAST|CODE-RL-*|INFRA-NO-SECRETS-IN-CODE) CLASS=crit ;;
        DDD-*|EIP-*|SOLID-*|CLEAN-ARCH-*|ARCH-*|CODE-OB-*|GRASP-*|CODE-AR-*|CODE-CC-*|CODE-API-*) CLASS=important ;;
        *) CLASS=style ;;
    esac
}
declare -A SEEN_ID=()
for id in "${ORDER[@]+"${ORDER[@]}"}" "${UNIVERSAL[@]+"${UNIVERSAL[@]}"}" "${STACK_L1[@]+"${STACK_L1[@]}"}"; do
    [ -n "${SEEN_ID[$id]+_}" ] && continue
    SEEN_ID["$id"]=1
    classify "$id"
    case "$CLASS" in
        crit) CRIT+=("$id") ;; important) IMPORTANT+=("$id") ;; style) STYLE+=("$id") ;;
    esac
done
bullets() { # ids... -> "- ID: Summary" lines, annotating locked principles
    local id
    for id in "$@"; do
        local tag=""; [ -n "${LOCKED[$id]+_}" ] && tag=" *(required by your organization)*"
        echo "- $id: ${PC_SUMMARY[$id]:--}$tag"
    done
}

# ── 7. REVIEW.md (Claude Code Review), about 10,000 characters ───────────────────────────────
if [ "$CLAUDE" = 1 ]; then
    budget=10000
    head_txt="$MARKER"$'\n# Code Review Rules\n'
    body="$head_txt"
    add_section() { # title ids...
        local title="$1"; shift
        [ "$#" -gt 0 ] || return 0
        local sect=$'\n## '"$title"$'\n\n' line
        while IFS= read -r line; do
            if [ $(( ${#body} + ${#sect} + ${#line} + 1 )) -gt "$budget" ]; then break; fi
            sect+="$line"$'\n'
        done < <(bullets "$@")
        [ "${#sect}" -gt $(( 14 + ${#title} )) ] && body+="$sect"
    }
    add_section "Critical - Always flag these" "${CRIT[@]+"${CRIT[@]}"}"
    add_section "Important - Flag when violated" "${IMPORTANT[@]+"${IMPORTANT[@]}"}"
    add_section "Style - Flag as nits" "${STYLE[@]+"${STYLE[@]}"}"
    write_file "$ROOT/REVIEW.md" "${body%$'\n'}"
else
    delete_generated "$ROOT/REVIEW.md"
fi

# ── 8. agent-neutral review.md ───────────────────────────────────────────────────────────────
if [ "$AGENTS" = 1 ]; then
    doc="$MARKER"$'\n'"<!-- principles-hash: $HASH -->"$'\n'"<!-- principles-stacks: $STACKS -->"$'\n'
    doc+='# Code review principles

Review the change against the principles below. Report only violations you can point to: name
the principle ID, the file and line, and a concrete fix. Skip stylistic preferences where
reasonable engineers disagree and nothing breaks.

**Before you review:** run `bash .agents/principles-catalog/bin/emit.sh --check`. If it exits
non-zero this list is stale: run `/dot-scout` (or `bash .agents/principles-catalog/bin/emit.sh`)
and read this file again.

**Going deeper:** for what a violation looks like, run
`bash .agents/principles-catalog/bin/context.sh <ID>...` for the principles that apply to the
change. For a full review with a findings report and an optional fix workflow, run `/dot-audit`.

**Scope:** this is the union of the principles that apply anywhere in the repository. A
`.principles` file in a subdirectory can exclude some of them for that subtree; check a path
with `bash .agents/principles-catalog/bin/resolve.sh --format explain <path>`.
'
    [ "${#CRIT[@]}" -gt 0 ]      && doc+=$'\n## Critical - always flag\n\n'"$(bullets "${CRIT[@]}")"$'\n'
    [ "${#IMPORTANT[@]}" -gt 0 ] && doc+=$'\n## Important - flag when violated\n\n'"$(bullets "${IMPORTANT[@]}")"$'\n'
    [ "${#STYLE[@]}" -gt 0 ]     && doc+=$'\n## Style - flag as nits\n\n'"$(bullets "${STYLE[@]}")"$'\n'
    if [ "${#WAIVERS[@]}" -gt 0 ]; then
        doc+=$'\n## Waivers - do not flag until the date\n\n'
        declare -A W_SEEN=()
        for w in "${WAIVERS[@]}"; do
            IFS='|' read -r wid wuntil wreason wdir <<< "$w"
            [ -n "${W_SEEN[$wid|$wdir]+_}" ] && continue; W_SEEN["$wid|$wdir"]=1
            doc+="- $wid until $wuntil in \`$wdir\`: $wreason"$'\n'
        done
    fi
    if [ "${#OVERRIDES[@]}" -gt 0 ]; then
        doc+=$'\n## Locked principles that a project tried to exclude\n\nThese stay in force. Flag the exclusion itself.\n\n'
        for o in "${OVERRIDES[@]}"; do
            IFS='|' read -r oid ofile <<< "$o"
            doc+="- $oid (excluded in \`$ofile\`)"$'\n'
        done
    fi
    write_file "$REVIEW_MD" "${doc%$'\n'}"

    # AGENTS.md: a short managed block pointing at review.md. Uninstall removes it by these exact
    # markers (and deletes AGENTS.md if nothing else is left), so a created file has no heading.
    block='<!-- .principles:start -->
## Code review

<!-- generated by dot-scout - do not edit; re-run dot-scout to refresh -->
When asked to review code or changes, follow `.agents/instructions/review.md`. It is generated
from this repository'"'"'s `.principles` files. Run `bash .agents/principles-catalog/bin/emit.sh --check`
first; if it reports stale files, run `/dot-scout`.
<!-- .principles:end -->'
    agents_md="$ROOT/AGENTS.md"
    if [ "$DRY" = 1 ]; then
        WRITTEN+=("AGENTS.md (dry run, managed block)")
    elif [ -f "$agents_md" ] && grep -q '^<!-- \.principles:start' "$agents_md"; then
        awk -v block="$block" '
            /^<!-- \.principles:start/ { print block; skip = 1; next }
            skip && /^<!-- \.principles:end/ { skip = 0; next }
            !skip { print }' "$agents_md" > "$agents_md.tmp" && mv "$agents_md.tmp" "$agents_md"
        WRITTEN+=("AGENTS.md (managed block updated)")
    elif [ -f "$agents_md" ]; then
        { printf '\n'; printf '%s\n' "$block"; } >> "$agents_md"
        WRITTEN+=("AGENTS.md (managed block appended)")
    else
        printf '%s\n' "$block" > "$agents_md"
        WRITTEN+=("AGENTS.md (created)")
    fi
fi

# Record that this project has been scouted, so `install.sh vendor` knows to refresh the generated
# files. Only when install.cfg already exists: creating it would turn off signal-file detection.
if [ "$DRY" = 0 ] && [ -f "$CFG" ] && ! grep -qx 'scout' "$CFG"; then
    echo 'scout' >> "$CFG"
fi

# ── 9. report ────────────────────────────────────────────────────────────────────────────────
echo "Active principles: ${#ORDER[@]}. Listed in the review files, with the always-applied universal and stack principles: ${#CRIT[@]} critical, ${#IMPORTANT[@]} important, ${#STYLE[@]} style"
echo "Tools: copilot=$COPILOT claude=$CLAUDE agents=$AGENTS"
echo "Written:"
for w in "${WRITTEN[@]+"${WRITTEN[@]}"}"; do echo "  $w"; done
if [ "${#DELETED[@]}" -gt 0 ]; then
    echo "Removed (no longer apply):"
    for d in "${DELETED[@]}"; do echo "  $d"; done
fi
if [ "${#WARNINGS[@]}" -gt 0 ]; then
    echo "Warnings:"
    printf '%s\n' "${WARNINGS[@]}" | awk '!seen[$0]++' | sed 's/^/  /'
fi
exit 0
